import { StyleSheet } from 'react-native';
import { colors, spacing, fontSizes, radius } from '../theme';

const styles = StyleSheet.create({
  container: {
    marginBottom: spacing.lg,
    padding: spacing.lg,
    borderRadius: radius.xl,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.shadow,
    shadowOpacity: 0.25,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 12 },
    elevation: 4,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.xs,
    gap: spacing.sm,
  },
  heading: {
    fontSize: fontSizes.lg,
    fontWeight: '700',
    color: colors.text,
    flex: 1,
  },
  caption: {
    fontSize: fontSizes.sm,
    color: colors.mutedText,
    marginBottom: spacing.xs,
  },
  moodHelper: {
    fontSize: fontSizes.xs,
    color: colors.mutedText,
    marginBottom: spacing.md,
  },
  moodSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    shadowColor: colors.shadow,
    shadowOpacity: 0.15,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  moodSelectorPressed: {
    transform: [{ scale: 0.97 }],
    opacity: 0.9,
  },
  moodSelectorDisabled: {
    opacity: 0.6,
  },
  moodSelectorLabel: {
    fontSize: fontSizes.sm,
    fontWeight: '600',
    color: colors.text,
    marginRight: spacing.xs,
  },
  moodSelectorIcon: {
    fontSize: fontSizes.sm,
    color: colors.mutedText,
  },
  button: {
    alignSelf: 'flex-start',
    paddingHorizontal: spacing.lg,
    marginTop: spacing.sm,
    marginBottom: spacing.sm,
  },
  suggestionBox: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.lg,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    marginTop: spacing.md,
  },
  suggestionText: {
    fontSize: fontSizes.md,
    color: colors.text,
    lineHeight: 22,
  },
  errorText: {
    marginTop: spacing.sm,
    color: colors.error,
    fontSize: fontSizes.sm,
  },
  inlineContainer: {
    marginTop: spacing.md,
    marginBottom: spacing.md,
    alignItems: 'flex-start',
    gap: spacing.xs,
  },
  inlineControls: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: spacing.sm,
  },
  inlineMoodSelector: {
    shadowOpacity: 0,
    elevation: 0,
  },
  inlineButton: {
    alignSelf: 'flex-start',
    marginTop: 0,
    marginBottom: 0,
    paddingHorizontal: spacing.md,
  },
  inlineCaption: {
    fontSize: fontSizes.xs,
    color: colors.mutedText,
  },
  inlineHint: {
    fontSize: fontSizes.xs,
    color: colors.mutedText,
  },
  inlineError: {
    fontSize: fontSizes.xs,
    color: colors.error,
  },
  moodModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(75, 46, 18, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.lg,
  },
  moodModalScrim: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'transparent',
  },
  moodModalCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.lg,
    shadowColor: colors.shadow,
    shadowOpacity: 0.35,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 14 },
    elevation: 6,
  },
  moodModalTitle: {
    fontSize: fontSizes.lg,
    fontWeight: '700',
    color: colors.text,
  },
  moodModalCaption: {
    fontSize: fontSizes.sm,
    color: colors.mutedText,
    marginTop: spacing.xs,
    marginBottom: spacing.md,
  },
  moodOption: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceMuted,
    marginBottom: spacing.sm,
  },
  moodOptionActive: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(230, 138, 46, 0.18)',
  },
  moodOptionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.xs,
    gap: spacing.xs,
  },
  moodOptionLabel: {
    fontSize: fontSizes.md,
    fontWeight: '600',
    color: colors.text,
  },
  moodOptionBadge: {
    backgroundColor: colors.primary,
    color: colors.primaryText,
    fontSize: fontSizes.xs,
    fontWeight: '700',
    paddingHorizontal: spacing.xs,
    paddingVertical: 2,
    borderRadius: 999,
  },
  moodOptionHint: {
    fontSize: fontSizes.xs,
    color: colors.mutedText,
  },
});

export default styles;
