import { StyleSheet } from 'react-native';
import { colors, spacing, fontSizes, radius } from '../theme';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.canvas,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xl,
    backgroundColor: colors.canvas,
  },
  container: {
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
  },
  heroCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.xl,
    marginBottom: spacing.lg,
    shadowColor: colors.shadow,
    shadowOpacity: 0.3,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 4,
    alignItems: 'center',
  },
  title: {
    fontSize: fontSizes.xxl,
    fontWeight: '800',
    color: colors.text,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: fontSizes.md,
    color: colors.mutedText,
    marginTop: spacing.xs,
    textAlign: 'center',
  },
  heroButton: {
    marginTop: spacing.lg,
    backgroundColor: colors.primary,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.sm,
    minWidth: 220,
  },
  heroButtonText: {
    textAlign: 'center',
    color: colors.primaryText,
    fontSize: fontSizes.md,
    fontWeight: '700',
  },
  card: {
    backgroundColor: 'transparent',
    paddingHorizontal: 0,
    paddingVertical: spacing.lg,
    marginBottom: spacing.lg,
  },
  statusPill: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(230, 138, 46, 0.16)',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: 999,
    marginBottom: spacing.sm,
  },
  statusText: {
    color: colors.primaryDark,
    fontSize: fontSizes.sm,
    fontWeight: '600',
  },
  infoPill: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.surfaceMuted,
    marginBottom: spacing.md,
  },
  infoText: {
    fontSize: fontSizes.sm,
    color: colors.mutedText,
  },
  aiBlock: {
    marginTop: spacing.md,
    marginBottom: spacing.md,
  },
  sectionCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    shadowColor: colors.shadow,
    shadowOpacity: 0.15,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  sectionTitle: {
    fontSize: fontSizes.lg,
    fontWeight: '700',
    color: colors.text,
    marginBottom: spacing.md,
  },
  sectionHeader: {
    marginBottom: spacing.lg,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    gap: spacing.sm,
  },
  sectionMeta: {
    fontSize: fontSizes.xs,
    color: colors.mutedText,
    fontWeight: '600',
  },
  sectionHint: {
    fontSize: fontSizes.xs,
    color: colors.mutedText,
    marginTop: spacing.xs,
  },
  slotScrollWrapper: {
    marginBottom: spacing.lg,
  },
  slotScrollContent: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xs,
  },
  slotCard: {
    minWidth: 190,
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    marginRight: spacing.sm,
  },
  slotCardActive: {
    backgroundColor: 'rgba(230, 138, 46, 0.18)',
  },
  slotDate: {
    fontSize: fontSizes.sm,
    fontWeight: '700',
    color: colors.text,
    textTransform: 'capitalize',
  },
  slotTime: {
    marginTop: spacing.xs,
    fontSize: fontSizes.md,
    color: colors.text,
    fontWeight: '600',
  },
  slotDuration: {
    marginTop: spacing.xs,
    fontSize: fontSizes.xs,
    color: colors.mutedText,
    fontWeight: '600',
  },
  selectedSlotInline: {
    marginTop: spacing.md,
  },
  selectedSlotLabel: {
    fontSize: fontSizes.xs,
    color: colors.mutedText,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  selectedSlotText: {
    marginTop: spacing.xs,
    fontSize: fontSizes.md,
    fontWeight: '600',
    color: colors.text,
  },
  selectedSlotDuration: {
    marginTop: spacing.xs,
    fontSize: fontSizes.xs,
    color: colors.mutedText,
  },
  moodCardsWrap: {
    flexDirection: 'column',
    gap: spacing.sm,
    marginTop: spacing.md,
    marginBottom: spacing.lg,
  },
  moodCard: {
    width: '100%',
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    padding: spacing.md,
    shadowColor: colors.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  moodCardActive: {
    backgroundColor: 'rgba(230, 138, 46, 0.18)',
    shadowOpacity: 0.16,
  },
  moodCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.xs,
  },
  moodCardHeaderText: {
    flexShrink: 1,
    paddingRight: spacing.sm,
  },
  moodCardLabel: {
    fontSize: fontSizes.md,
    fontWeight: '700',
    color: colors.text,
  },
  moodCardCategory: {
    marginTop: 2,
    fontSize: fontSizes.xs,
    color: colors.mutedText,
    fontWeight: '600',
  },
  moodCardActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  moodCardBadge: {
    backgroundColor: colors.primary,
    color: colors.primaryText,
    fontSize: fontSizes.xs,
    fontWeight: '700',
    paddingHorizontal: spacing.xs,
    paddingVertical: 2,
    borderRadius: 999,
  },
  moodCardSummary: {
    fontSize: fontSizes.sm,
    color: colors.mutedText,
  },
  moodCardHelper: {
    marginTop: spacing.xs,
    fontSize: fontSizes.xs,
    color: colors.mutedText,
  },
  moodCardIcon: {
    fontSize: fontSizes.lg,
    color: colors.mutedText,
  },
  moodCardIconActive: {
    color: colors.primaryDark,
  },
  moodEditorCard: {
    shadowColor: colors.shadow,
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  moodEditorTitle: {
    fontSize: fontSizes.lg,
    fontWeight: '700',
    color: colors.text,
  },
  moodEditorHint: {
    fontSize: fontSizes.xs,
    color: colors.mutedText,
    marginTop: spacing.xs,
    marginBottom: spacing.md,
  },
  moodEditorLabel: {
    fontSize: fontSizes.sm,
    color: colors.mutedText,
    marginBottom: spacing.xs,
    marginTop: spacing.md,
  },
  moodEditorInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontSize: fontSizes.md,
    color: colors.text,
    backgroundColor: colors.surfaceMuted,
  },
  moodEditorMultiline: {
    minHeight: 100,
    textAlignVertical: 'top',
  },
  moodPrimaryButton: {
    marginTop: spacing.sm,
  },
  moodHelper: {
    fontSize: fontSizes.sm,
    color: colors.mutedText,
    marginBottom: spacing.lg,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(75, 46, 18, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.lg,
  },
  detailsModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(75, 46, 18, 0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.lg,
  },
  detailsModalScrim: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  detailsModalCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.lg,
    shadowColor: colors.shadow,
    shadowOpacity: 0.25,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 5,
  },
  detailsModalTitle: {
    fontSize: fontSizes.lg,
    fontWeight: '700',
    color: colors.text,
  },
  detailsModalSummary: {
    marginTop: spacing.sm,
    fontSize: fontSizes.sm,
    color: colors.text,
    lineHeight: 22,
  },
  detailsModalDescription: {
    marginTop: spacing.sm,
    fontSize: fontSizes.sm,
    color: colors.mutedText,
    lineHeight: 20,
  },
  detailsModalButton: {
    marginTop: spacing.lg,
  },
  modalAvoiding: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  modalCard: {
    backgroundColor: colors.background,
    borderRadius: radius.lg,
    padding: spacing.lg,
    width: '100%',
    maxWidth: 520,
    maxHeight: '90%',
    overflow: 'hidden',
  },
  modalScrollContent: {
    paddingBottom: spacing.xl,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  modalTitle: {
    fontSize: fontSizes.lg,
    fontWeight: '700',
    color: colors.text,
  },
  modalCloseButton: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  modalCloseText: {
    color: colors.primary,
    fontSize: fontSizes.md,
    fontWeight: '600',
  },
  modalLabel: {
    fontSize: fontSizes.sm,
    color: colors.mutedText,
    marginBottom: spacing.xs,
    marginTop: spacing.md,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontSize: fontSizes.md,
    color: colors.text,
    backgroundColor: colors.surface,
  },
  modalNotesInput: {
    minHeight: 100,
    textAlignVertical: 'top',
  },
  modalDateButton: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing.md,
    backgroundColor: colors.surfaceMuted,
  },
  modalDateText: {
    fontSize: fontSizes.md,
    color: colors.text,
  },
  suggestionsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -spacing.xs,
  },
  suggestionChip: {
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.md,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceMuted,
    marginHorizontal: spacing.xs,
    marginBottom: spacing.xs,
  },
  suggestionEmptyText: {
    fontSize: fontSizes.sm,
    color: colors.mutedText,
  },
  suggestionChipSelected: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(230, 138, 46, 0.18)',
  },
  suggestionText: {
    fontSize: fontSizes.sm,
    color: colors.text,
    fontWeight: '600',
  },
  modalHint: {
    fontSize: fontSizes.sm,
    color: colors.mutedText,
  },
  modalHintWarning: {
    color: colors.error,
    fontWeight: '600',
  },
  modalPrimaryButton: {
    marginTop: spacing.lg,
  },
  modalSecondaryButton: {
    marginTop: spacing.sm,
    backgroundColor: '#BFA386',
  },
  helperText: {
    fontSize: fontSizes.xs,
    color: colors.mutedText,
  },
});

export default styles;
