import { StyleSheet } from 'react-native';
import { colors, spacing, fontSizes, radius } from '../theme';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.canvas,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xl,
  },
  container: {
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
  },
  heroCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.xl,
    marginBottom: spacing.lg,
    shadowColor: colors.shadow,
    shadowOpacity: 0.3,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 14 },
    elevation: 4,
  },
  heroBadge: {
    alignSelf: 'flex-start',
    backgroundColor: colors.surfaceMuted,
    color: colors.primaryDark,
    fontSize: fontSizes.xs,
    fontWeight: '700',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xxs,
    borderRadius: 999,
    letterSpacing: 0.6,
    marginBottom: spacing.sm,
  },
  title: {
    fontSize: fontSizes.xxl,
    fontWeight: '800',
    color: colors.text,
  },
  subtitle: {
    fontSize: fontSizes.md,
    color: colors.mutedText,
    marginTop: spacing.xs,
  },
  sectionIntro: {
    marginTop: spacing.sm,
    fontSize: fontSizes.sm,
    color: colors.mutedText,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.xl,
    marginBottom: spacing.lg,
    shadowColor: colors.shadow,
    shadowOpacity: 0.25,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 12 },
    elevation: 4,
  },
  cardTitle: {
    fontSize: fontSizes.lg,
    fontWeight: '700',
    color: colors.text,
  },
  cardSubtitle: {
    fontSize: fontSizes.sm,
    color: colors.mutedText,
    marginTop: spacing.xs,
    marginBottom: spacing.lg,
  },
  emojiSection: {
    marginBottom: spacing.lg,
  },
  emojiLabel: {
    fontSize: fontSizes.md,
    fontWeight: '700',
    color: colors.text,
  },
  emojiHint: {
    marginTop: spacing.xs,
    fontSize: fontSizes.sm,
    color: colors.mutedText,
  },
  emojiGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  emojiOption: {
    width: 56,
    height: 56,
    borderRadius: radius.lg,
    borderWidth: 2,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
  },
  emojiOptionSelected: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(230, 138, 46, 0.18)',
  },
  emojiOptionText: {
    fontSize: 28,
    fontWeight: '600',
  },
  emojiOptionTextSelected: {
    fontWeight: '800',
  },
  successPill: {
    backgroundColor: 'rgba(230, 138, 46, 0.16)',
    borderRadius: 999,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.md,
    alignSelf: 'flex-start',
    marginBottom: spacing.sm,
  },
  successText: {
    fontSize: fontSizes.sm,
    color: colors.primaryDark,
    fontWeight: '600',
  },
  loadingWrapper: {
    paddingVertical: spacing.lg,
  },
  field: {
    marginBottom: spacing.md,
  },
  sectionDivider: {
    height: 1,
    backgroundColor: colors.border,
    marginVertical: spacing.lg,
  },
  preferenceTitle: {
    fontSize: fontSizes.md,
    fontWeight: '700',
    color: colors.text,
  },
  preferenceHint: {
    fontSize: fontSizes.sm,
    color: colors.mutedText,
    marginTop: spacing.xs,
    marginBottom: spacing.sm,
  },
  preferenceSubtitle: {
    marginTop: spacing.md,
    marginBottom: spacing.xs,
    fontSize: fontSizes.sm,
    color: colors.mutedText,
    fontWeight: '600',
  },
  preferenceModeWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: spacing.xs,
    marginBottom: spacing.sm,
  },
  preferenceModeChip: {
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.md,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceMuted,
    marginRight: spacing.xs,
    marginBottom: spacing.xs,
  },
  preferenceModeChipSelected: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(230, 138, 46, 0.18)',
  },
  preferenceModeChipDisabled: {
    opacity: 0.5,
  },
  preferenceModeChipText: {
    fontSize: fontSizes.sm,
    color: colors.text,
    fontWeight: '600',
  },
  preferenceModeChipTextSelected: {
    color: colors.primaryDark,
  },
  preferenceModeChipTextDisabled: {
    color: colors.mutedText,
  },
  customPreferenceSection: {
    marginTop: spacing.sm,
  },
  durationSliderBlock: {
    marginTop: spacing.sm,
    marginBottom: spacing.md,
  },
  preferenceInfoCard: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing.md,
    backgroundColor: colors.surfaceMuted,
    marginBottom: spacing.md,
  },
  preferenceInfoTitle: {
    fontSize: fontSizes.md,
    fontWeight: '700',
    color: colors.text,
  },
  preferenceInfoText: {
    fontSize: fontSizes.sm,
    color: colors.mutedText,
    marginTop: spacing.xs,
  },
  locationGroup: {
    marginBottom: spacing.md,
  },
  locationHint: {
    fontSize: fontSizes.xs,
    color: colors.mutedText,
    marginTop: spacing.xs,
    marginBottom: spacing.xs,
  },
  locationChipsWrap: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    justifyContent: 'space-between',
    marginTop: spacing.xs,
  },
  locationChip: {
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.xs,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationChipSelected: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(230, 138, 46, 0.18)',
  },
  locationChipText: {
    fontSize: fontSizes.sm,
    color: colors.text,
  },
  locationChipTextSelected: {
    fontWeight: '700',
    color: colors.primaryDark,
  },
  followList: {
    marginTop: spacing.sm,
  },
  followOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    marginBottom: spacing.xs,
  },
  followOptionSelected: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(230, 138, 46, 0.18)',
  },
  followOptionEmoji: {
    fontSize: fontSizes.xl,
    marginRight: spacing.sm,
  },
  followOptionBody: {
    flex: 1,
  },
  followOptionName: {
    fontSize: fontSizes.md,
    fontWeight: '700',
    color: colors.text,
  },
  followOptionHint: {
    fontSize: fontSizes.xs,
    color: colors.mutedText,
    marginTop: spacing.xxs,
  },
  genderGroup: {
    marginBottom: spacing.md,
  },
  genderChipsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: spacing.xs,
  },
  genderChip: {
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.md,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceMuted,
    marginRight: spacing.xs,
    marginBottom: spacing.xs,
  },
  genderChipSelected: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(230, 138, 46, 0.18)',
  },
  genderChipText: {
    fontSize: fontSizes.sm,
    color: colors.text,
  },
  genderChipTextSelected: {
    fontWeight: '700',
    color: colors.primaryDark,
  },
  dayTimeList: {
    marginTop: spacing.xs,
  },
  dayAccordion: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    marginBottom: spacing.sm,
    overflow: 'hidden',
  },
  dayAccordionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.sm,
  },
  dayAccordionHeaderMain: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  dayAccordionHeaderExpanded: {
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  dayAccordionSwitch: {
    marginLeft: spacing.sm,
    transform: [{ scaleX: 0.85 }, { scaleY: 0.85 }],
  },
  dayAccordionBody: {
    padding: spacing.sm,
    backgroundColor: colors.surfaceMuted,
  },
  dayAccordionBodyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  dayTimeHeaderTextWrap: {
    flex: 1,
    marginRight: spacing.sm,
  },
  dayTimeLabel: {
    fontSize: fontSizes.sm,
    fontWeight: '700',
    color: colors.text,
  },
  dayTimeSummary: {
    fontSize: fontSizes.xs,
    color: colors.mutedText,
  },
  dayToggleHint: {
    fontSize: fontSizes.xs,
    color: colors.mutedText,
    flex: 1,
    marginRight: spacing.sm,
  },
  timeSlotCard: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    padding: spacing.sm,
    marginBottom: spacing.sm,
    backgroundColor: colors.surfaceMuted,
  },
  timeSlotHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.xs,
  },
  timeSlotLabel: {
    fontSize: fontSizes.sm,
    fontWeight: '700',
    color: colors.text,
  },
  timeSlotRemove: {
    fontSize: fontSizes.xs,
    color: colors.error,
    fontWeight: '600',
  },
  dayEmptyHint: {
    fontSize: fontSizes.xs,
    color: colors.mutedText,
    marginBottom: spacing.sm,
  },
  timePresetWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: spacing.xs,
    marginBottom: spacing.xs,
  },
  timePresetChip: {
    width: '48%',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    marginBottom: spacing.xs,
    backgroundColor: colors.surface,
  },
  timePresetChipInner: {
    width: '100%',
  },
  timePresetChipHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.xxs,
  },
  timePresetChipSelected: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(230, 138, 46, 0.18)',
  },
  timePresetLabel: {
    fontSize: fontSizes.xs,
    fontWeight: '600',
    color: colors.text,
    textAlign: 'center',
  },
  timePresetLabelSelected: {
    color: colors.primaryDark,
  },
  timePresetRange: {
    fontSize: fontSizes.xs,
    color: colors.mutedText,
    textAlign: 'center',
  },
  timePresetRangeSelected: {
    color: colors.primaryDark,
  },
  durationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.xs,
  },
  durationTitle: {
    fontSize: fontSizes.sm,
    fontWeight: '700',
    color: colors.text,
  },
  timeSelectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: spacing.xs,
    marginBottom: spacing.xs,
  },
  timeSelectionButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    marginRight: spacing.xs,
    backgroundColor: colors.surface,
    shadowColor: colors.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  timeSelectionButtonRight: {
    marginRight: 0,
  },
  timeSelectionLabel: {
    fontSize: fontSizes.xxs,
    color: colors.mutedText,
    marginBottom: spacing.xxs,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  timeSelectionValue: {
    fontSize: fontSizes.sm,
    fontWeight: '700',
    color: colors.text,
  },
  inlineTimePicker: {
    marginTop: spacing.xs,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    padding: spacing.xs,
  },
  timePickerCloseButton: {
    alignSelf: 'flex-end',
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
  },
  timePickerCloseText: {
    color: colors.primaryDark,
    fontWeight: '600',
  },
  timeSelectionClear: {
    fontSize: fontSizes.xs,
    color: colors.mutedText,
    textDecorationLine: 'underline',
  },
  preferenceFootnote: {
    marginTop: spacing.xs,
    marginBottom: spacing.sm,
    fontSize: fontSizes.xs,
    color: colors.mutedText,
  },
  timeSelectionClearDisabled: {
    opacity: 0.4,
  },
  saveButton: {
    marginTop: spacing.md,
    alignSelf: 'flex-start',
    paddingHorizontal: spacing.lg,
  },
  familyCard: {
    backgroundColor: colors.surface,
  },
  familyInfoText: {
    fontSize: fontSizes.sm,
    color: colors.mutedText,
    marginBottom: spacing.xs,
  },
  familyInfoValue: {
    fontWeight: '700',
    color: colors.text,
  },
  copyButton: {
    marginTop: spacing.sm,
    alignSelf: 'flex-start',
    paddingHorizontal: spacing.lg,
  },
});

export default styles;
