import { StyleSheet } from 'react-native';
import { colors, spacing, fontSizes, radius } from '../theme';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.canvas,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xl,
    backgroundColor: colors.canvas,
  },
  container: {
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
    gap: spacing.lg,
  },
  heroCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    borderWidth: 0,
    padding: spacing.xl,
    gap: spacing.sm,
    shadowColor: colors.shadow,
    shadowOpacity: 0.12,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 3,
  },
  messagesCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    borderWidth: 0,
    padding: spacing.lg,
    gap: spacing.sm,
    shadowColor: colors.shadow,
    shadowOpacity: 0.1,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  title: {
    fontSize: fontSizes.xxl,
    fontWeight: '800',
    color: colors.text,
  },
  subtitle: {
    fontSize: fontSizes.md,
    color: colors.mutedText,
    marginTop: spacing.xs,
  },
  infoText: {
    fontSize: fontSizes.sm,
    color: colors.mutedText,
  },
  statusText: {
    color: colors.primaryDark,
    fontSize: fontSizes.sm,
    fontWeight: '600',
  },
  statusPill: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(230, 138, 46, 0.16)',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: 999,
  },
  infoPill: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.surfaceMuted,
  },
  sectionGroup: {
    marginBottom: spacing.xl,
    gap: spacing.md,
  },
  sectionCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    borderWidth: 2,
    borderColor: colors.border,
    padding: spacing.lg,
    gap: spacing.md,
    shadowColor: colors.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  eventList: {
    gap: spacing.md,
  },
  autoSuggestionList: {
    gap: spacing.md,
  },
  emptyCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.shadow,
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 4 },
    elevation: 1,
    gap: spacing.xs,
  },
  emptyTitle: {
    fontSize: fontSizes.md,
    fontWeight: '600',
    color: colors.text,
  },
  emptySubtitle: {
    fontSize: fontSizes.sm,
    color: colors.mutedText,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
  },
  sectionHeaderTextWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  sectionHeaderText: {
    flex: 1,
    gap: spacing.xs,
  },
  sectionCollapseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionCollapseIcon: {
    fontSize: fontSizes.lg,
    color: colors.mutedText,
  },
  sectionBadge: {
    width: 48,
    height: 48,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
  },
  sectionBadgeText: {
    fontSize: fontSizes.md,
    fontWeight: '700',
    color: colors.text,
  },
  sectionTitle: {
    fontSize: fontSizes.lg,
    fontWeight: '700',
    color: colors.text,
  },
  sectionHint: {
    fontSize: fontSizes.sm,
    color: colors.mutedText,
    marginTop: spacing.xs,
  },
  sectionDivider: {
    height: 2,
    borderRadius: 999,
    backgroundColor: colors.border,
    marginVertical: spacing.sm,
  },
  eventCard: {
    borderRadius: radius.md,
    padding: spacing.lg,
    backgroundColor: colors.surface,
    gap: spacing.xs,
    shadowColor: colors.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  eventHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  eventHeaderText: {
    flex: 1,
  },
  eventToggle: {
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xs,
    borderRadius: radius.md,
  },
  eventToggleIcon: {
    fontSize: fontSizes.lg,
    color: colors.mutedText,
  },
  eventToggleIconActive: {
    color: colors.primary,
  },
  eventTitle: {
    fontSize: fontSizes.lg,
    fontWeight: '700',
    color: colors.text,
    marginBottom: spacing.xs,
  },
  eventChangeBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: radius.sm,
    marginBottom: spacing.xs,
    backgroundColor: colors.surfaceMuted,
  },
  eventChangeBadgeUpdate: {
    backgroundColor: 'rgba(230, 138, 46, 0.2)',
  },
  eventChangeBadgeCancel: {
    backgroundColor: 'rgba(209, 67, 36, 0.18)',
  },
  eventChangeBadgeText: {
    fontSize: fontSizes.xs,
    fontWeight: '700',
    color: colors.text,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  eventTime: {
    fontSize: fontSizes.md,
    color: colors.text,
    marginBottom: spacing.xs,
  },
  eventDescription: {
    fontSize: fontSizes.sm,
    color: colors.mutedText,
    marginBottom: spacing.xs,
  },
  eventMeta: {
    fontSize: fontSizes.sm,
    color: colors.mutedText,
    marginBottom: spacing.xs,
  },
  approvalRow: {
    marginBottom: spacing.sm,
  },
  approvalBadges: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: spacing.xs,
    marginTop: spacing.xs,
  },
  approvalBadge: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  approvalBadgePending: {
    borderColor: colors.border,
  },
  approvalBadgeApproved: {
    borderColor: colors.success,
  },
  approvalBadgeUnknown: {
    borderColor: colors.border,
    opacity: 0.6,
  },
  approvalEmojiText: {
    fontSize: 22,
  },
  eventDetails: {
    marginTop: spacing.sm,
    gap: spacing.sm,
  },
  pendingChangeBox: {
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    backgroundColor: 'rgba(230, 138, 46, 0.12)',
    marginBottom: spacing.sm,
  },
  pendingChangeTitle: {
    fontSize: fontSizes.sm,
    fontWeight: '700',
    color: colors.text,
    marginBottom: spacing.xs,
  },
  pendingChangeText: {
    fontSize: fontSizes.sm,
    color: colors.text,
    marginBottom: spacing.xs,
  },
  eventActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  autoSuggestionCard: {
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
    backgroundColor: colors.surface,
    gap: spacing.sm,
    shadowColor: colors.shadow,
    shadowOpacity: 0.05,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 4 },
    elevation: 1,
  },
  autoSuggestionSponsorCard: {
    borderColor: '#0F6B81',
    backgroundColor: '#EEF9FF',
  },
  autoSuggestionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  autoSuggestionHeaderExtras: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  autoSuggestionTitle: {
    fontSize: fontSizes.lg,
    fontWeight: '700',
    color: colors.text,
    flex: 1,
  },
  sponsorTagPill: {
    alignSelf: 'flex-start',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: radius.sm,
    backgroundColor: '#D6F0FF',
  },
  sponsorTagText: {
    fontSize: fontSizes.xs,
    fontWeight: '700',
    color: '#0E5B73',
    letterSpacing: 0.5,
  },
  sponsorLogoBadge: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#0E5B73',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  sponsorLogoImage: {
    width: 44,
    height: 44,
    borderRadius: 18,
  },
  autoSuggestionTime: {
    fontSize: fontSizes.sm,
    color: colors.mutedText,
  },
  autoSuggestionPreview: {
    fontSize: fontSizes.sm,
    color: colors.text,
  },
  autoSuggestionSponsorPreview: {
    fontSize: fontSizes.sm,
    color: colors.text,
    fontWeight: '600',
  },
  autoSuggestionSponsorFootnote: {
    fontSize: fontSizes.xs,
    color: colors.mutedText,
    marginTop: spacing.xs,
  },
  autoSuggestionDescription: {
    fontSize: fontSizes.sm,
    color: colors.text,
    lineHeight: 20,
  },
  autoSuggestionEyeButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  autoSuggestionEyeIcon: {
    fontSize: fontSizes.md,
    color: colors.mutedText,
  },
  autoSuggestionActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  previewModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(75, 46, 18, 0.45)',
    justifyContent: 'center',
    padding: spacing.lg,
  },
  previewModalScrim: {
    ...StyleSheet.absoluteFillObject,
  },
  previewModalCard: {
    backgroundColor: colors.background,
    borderRadius: radius.lg,
    padding: spacing.xl,
    gap: spacing.md,
    shadowColor: colors.shadow,
    shadowOpacity: 0.15,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  previewModalTitle: {
    fontSize: fontSizes.lg,
    fontWeight: '700',
    color: colors.text,
  },
  previewModalDescription: {
    fontSize: fontSizes.md,
    color: colors.text,
    lineHeight: 22,
  },
  previewModalButton: {
    alignSelf: 'center',
    minWidth: 140,
  },
  previewModalPrice: {
    fontSize: fontSizes.md,
    fontWeight: '600',
    color: colors.text,
  },
  eventActionButton: {
    flexGrow: 1,
  },
  eventActionButtonPrimary: {
    minWidth: 160,
  },
  eventApproveButton: {
    backgroundColor: colors.primary,
  },
  eventRejectButton: {
    backgroundColor: colors.error,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(75, 46, 18, 0.45)',
    justifyContent: 'center',
    padding: spacing.lg,
  },
  modalAvoiding: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalWrapper: {
    width: '100%',
    maxWidth: 520,
    maxHeight: '90%',
  },
  modalCard: {
    backgroundColor: colors.background,
    borderRadius: radius.lg,
    padding: spacing.lg,
    gap: spacing.md,
  },
  modalTitle: {
    fontSize: fontSizes.lg,
    fontWeight: '700',
    color: colors.text,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontSize: fontSizes.md,
    color: colors.text,
    backgroundColor: colors.surface,
  },
  modalNotesInput: {
    minHeight: 80,
    textAlignVertical: 'top',
  },
  modalLabel: {
    fontSize: fontSizes.sm,
    color: colors.mutedText,
  },
  modalDateButton: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing.md,
    backgroundColor: colors.surfaceMuted,
  },
  modalDateText: {
    fontSize: fontSizes.md,
    color: colors.text,
  },
  calendarPickerWrapper: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    marginTop: spacing.sm,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    overflow: 'hidden',
  },
  calendarPicker: {
    width: '100%',
    alignSelf: 'center',
    transform: [{ scaleX: 0.85 }, { scaleY: 0.85 }],
  },
  inlineTimePicker: {
    marginTop: spacing.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    gap: spacing.xs,
    alignSelf: 'center',
    width: '100%',
  },
  inlineTimeSpinner: {
    width: '100%',
    transform: [{ scaleX: 0.9 }, { scaleY: 0.9 }],
    alignSelf: 'center',
  },
  inlineTimePickerAction: {
    alignItems: 'flex-end',
  },
  inlineTimePickerClose: {
    fontSize: fontSizes.sm,
    color: colors.primary,
    fontWeight: '600',
  },
  cancelToggle: {
    backgroundColor: '#F5C88B',
    marginTop: spacing.md,
  },
  cancelToggleActive: {
    backgroundColor: colors.error,
    marginTop: spacing.md,
  },
  cancelHint: {
    fontSize: fontSizes.sm,
    color: colors.mutedText,
    marginTop: spacing.xs,
    marginBottom: spacing.sm,
  },
  modalPrimaryButton: {
    marginTop: spacing.sm,
  },
  modalSecondaryButton: {
    marginTop: spacing.xs,
    backgroundColor: '#BFA386',
  },
});

export default styles;
